server:
  port:
    8080
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:9090/eureka/,http://localhost:9091/eureka/ #eureka server服务url，用于客户端注册。eureka启动多个实例，高可用注册中心集群（理想情况下采用域名）
spring:
  application:
    name: user-service-consumer